import { useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { clsx } from 'clsx'
import { ArrowLeft, ShieldCheck, Play, FileCode2, FileText, Hash, Check } from '../components/icons'
import { RunHeader } from '../components/RunHeader'
import { RunSummaryFooter } from '../components/RunSummaryFooter'
import { MiniThumb } from '../components/MiniThumb'
import { Button, Chip } from '../components/primitives'
import { getRunTreeCounts } from '../lib/runFooter'
import { useRun } from '../store/RunProvider'
import type { DiffLine } from '../domain/types'

type Line = DiffLine

function DiffRow({ line }: { line: Line }) {
  const cls =
    line.kind === 'add' ? 'bg-state-green-soft' : line.kind === 'del' ? 'bg-state-red-soft' : ''
  const sign = line.kind === 'add' ? '+' : line.kind === 'del' ? '-' : ' '
  const signCls = line.kind === 'add' ? 'text-accent-text' : line.kind === 'del' ? 'text-ink-danger' : 'text-ink-tertiary'
  return (
    <div className={clsx('flex items-start font-mono text-xs leading-5', cls)}>
      <span className="w-10 shrink-0 select-none px-2 text-right text-ink-tertiary">{line.no}</span>
      <span className={clsx('w-4 shrink-0 select-none text-center', signCls)}>{sign}</span>
      <span className="whitespace-pre text-ink-primary">{line.text}</span>
    </div>
  )
}

function StatCard({ icon, title, children }: { icon: React.ReactNode; title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-lg border border-hairline bg-surface-raised p-3">
      <div className="mb-1 flex items-center gap-1.5 text-xs text-ink-secondary">
        <span className="text-ink-tertiary">{icon}</span>
        {title}
      </div>
      <div className="text-sm text-ink-primary">{children}</div>
    </div>
  )
}

export function PatchView() {
  const navigate = useNavigate()
  const run = useRun()
  const patch = run.patch

  useEffect(() => {
    if (!patch || patch.iteration !== run.fixIteration) run.loadPatch(run.fixIteration)
  }, [patch, run])

  const counts = getRunTreeCounts(run)
  const witnessCount = run.proofSet?.exploitWitnessIds.length ?? counts.witnesses
  const controlCount = run.proofSet?.legitimateControlIds.length ?? counts.controls

  if (!patch) {
    return (
      <>
        <RunHeader title="Exploit Witness" version="v3.2" primaryLabel="Resume run" />
        <div className="flex flex-1 items-center justify-center text-sm text-ink-secondary">Generating patch…</div>
      </>
    )
  }

  return (
    <>
      <RunHeader title="Exploit Witness" version="v3.2" primaryLabel="Resume run" />
      <div className="flex min-h-0 flex-1 overflow-hidden">
        <div className="scrollbar-thin min-w-0 flex-1 overflow-y-auto px-8 py-6">
          <button onClick={() => navigate('/proofset')} className="mb-5 flex items-center gap-1.5 rounded-md text-sm text-ink-secondary transition-[color,transform] duration-150 ease-out hover:text-ink-primary active:scale-[0.98] focus:outline-none focus-visible:ring-2 focus-visible:ring-ring">
            <ArrowLeft size={15} /> Back to run
          </button>
          <div className="max-w-3xl">
            <div className="flex items-center gap-3">
              <span className="flex h-9 w-9 items-center justify-center rounded-lg bg-green-50 text-accent-text">
                <ShieldCheck size={18} />
              </span>
              <h2 className="font-display text-2xl tracking-tight text-ink-primary">Verifier {patch.label}</h2>
              <Chip status="qa-review">AWAITING PROOF</Chip>
            </div>
            <p className="mt-1.5 text-sm text-ink-secondary">
              Generated by <span className="font-medium text-ink-primary">{patch.generatedBy}</span>
            </p>
            <p className="mt-3 text-sm text-ink-secondary-strong">{patch.description}</p>

            <div className="mt-5 overflow-hidden rounded-lg border border-hairline bg-surface-raised">
              <div className="flex items-center justify-between border-b border-hairline bg-surface px-4 py-2.5">
                <span className="flex min-w-0 items-center gap-2 font-mono text-xs text-ink-primary">
                  <FileCode2 size={14} className="text-ink-tertiary" />
                  <span className="truncate">{patch.filePath}</span>
                </span>
                <span className="font-mono text-xs">
                  <span className="text-accent-text">+{patch.added}</span> <span className="text-ink-danger">-{patch.removed}</span>
                </span>
              </div>
              <div className="overflow-x-auto py-2">
                {patch.diff.map((l, i) => (
                  <DiffRow key={i} line={l} />
                ))}
              </div>
            </div>

            <div className="mt-4 grid grid-cols-1 gap-3 xl:grid-cols-3">
              <StatCard icon={<FileText size={13} />} title="Patch summary">
                {patch.summary}
              </StatCard>
              <StatCard icon={<FileCode2 size={13} />} title="Files changed">
                1<div className="break-all text-xs text-ink-secondary">{patch.filePath}</div>
              </StatCard>
              <StatCard icon={<Hash size={13} />} title="Patch digest">
                <span className="break-all font-mono text-xs">{patch.patchDigest}</span>
              </StatCard>
            </div>

            <div className="mt-4 flex items-center gap-2 rounded-lg border border-hairline bg-surface px-4 py-3 text-sm">
              <Chip status="qa-review">AWAITING PROOF</Chip>
              <span className="text-ink-secondary-strong">This patch has not been proven yet.</span>
            </div>
          </div>
        </div>

        {/* right panel */}
        <aside className="scrollbar-thin flex min-h-0 w-80 shrink-0 flex-col overflow-y-auto border-l border-hairline bg-background px-5 py-5">
          <div className="flex items-center gap-2">
            <ShieldCheck size={16} className="text-accent-text" />
            <h3 className="font-display text-lg tracking-tight text-ink-primary">Selected for proof</h3>
          </div>
          <div className="mt-4 rounded-lg border border-hairline bg-surface-raised p-4">
            <div className="flex items-center justify-between text-sm">
              <span className="font-medium text-ink-primary">Proof set {witnessCount + controlCount}</span>
              <span className="text-ink-tertiary">Total {witnessCount + controlCount + (run.proofSet?.exploitFamilyVariantIds.length ?? 0)}</span>
            </div>
            <p className="mt-0.5 text-xs text-ink-secondary">Assembled from confirmed witnesses</p>
            <div className="mt-3 grid grid-cols-3 gap-2 text-center">
              {[
                ['Witnesses', String(witnessCount), 'text-accent-text'],
                ['Promising', String(counts.candidates), 'text-warn-text'],
                ['Controls', String(controlCount), 'text-ink-secondary-strong'],
              ].map(([l, v, c]) => (
                <div key={l} className="rounded-lg bg-surface px-2 py-2">
                  <div className={clsx('text-lg font-semibold', c)}>{v}</div>
                  <div className="text-2xs text-ink-tertiary">{l}</div>
                </div>
              ))}
            </div>
            <div className="mt-3 flex items-center justify-between border-t border-hairline pt-3 text-sm">
              <span className="text-ink-secondary">Protection target</span>
              <Chip status="witness">QA ForkPoint (ROOT)</Chip>
            </div>
          </div>

          <div className="mt-4 space-y-2">
            <div className="text-2xs font-semibold uppercase tracking-wide text-ink-tertiary">Next step</div>
            <div className="mb-2 text-sm text-ink-secondary-strong">{patch.label}</div>
            <Button variant="primary" size="md" className="w-full" icon={<Play size={14} />} onClick={() => navigate('/gate')}>
              Run proof set
            </Button>
          </div>

          <div className="mt-5">
            <div className="mb-2 text-2xs font-semibold uppercase tracking-wide text-ink-tertiary">Why this patch</div>
            <ul className="space-y-2 text-sm text-ink-secondary-strong">
              {patch.rationale.map((t) => (
                <li key={t} className="flex items-start gap-2">
                  <Check size={14} className="mt-0.5 shrink-0 text-accent-text" />
                  {t}
                </li>
              ))}
            </ul>
          </div>

        </aside>
      </div>
      <RunSummaryFooter
        stats={[
          { label: 'Witness', value: witnessCount, tone: 'green' },
          { label: 'Promising', value: counts.candidates, tone: 'warn' },
          { label: 'Controls', value: controlCount, tone: 'gray' },
        ]}
        total={counts.proofSetMembers || witnessCount + counts.candidates + controlCount}
        cards={[
          { icon: 'witness', label: 'Witness', value: witnessCount, onClick: () => navigate('/witness') },
          { icon: 'proofset', label: 'Proof set', value: counts.proofSetMembers, onClick: () => navigate('/proofset') },
          {
            icon: 'releaseproof',
            label: 'Release proof',
            value: counts.releaseProofs,
            onClick: () => navigate('/releaseproof'),
          },
          { icon: 'artifacts', label: 'Patch artifacts', value: patch ? 1 : 0, onClick: () => navigate('/artifacts') },
        ]}
        minimap={<MiniThumb variant="tree" />}
      />
    </>
  )
}
