/**
 * Single, explicit switch for where the Traceback UI gets its data.
 *
 * Set in `.env` (or the Vercel project env). Two knobs, both optional:
 *
 *   VITE_TRACEBACK_API       'http' (default) | 'mock'
 *   VITE_TRACEBACK_API_BASE  base path for the static API JSON (default '/api')
 *
 * - `http` (default): fetch the real, build-time data exported from repo
 *   artifacts (`frontend/public/api/*.json`, generated by
 *   `uv run python -m forkproof.api.export`). This is what ships on Vercel.
 * - `mock`: the in-memory demo dataset — handy for pure UI work with no data
 *   files present.
 */

export type ApiMode = 'http' | 'mock'

export const apiMode: ApiMode = import.meta.env.VITE_TRACEBACK_API === 'mock' ? 'mock' : 'http'

export const apiBase: string = (import.meta.env.VITE_TRACEBACK_API_BASE ?? '/api').replace(/\/+$/, '')
