export const DESIGN_PARTNER_INTAKE_SUMMARY = {
  title: 'Pilot intake package',
  status: 'Contract frozen',
  contractVersion: 'design-partner-evidence-contract-v1',
  templateAvailable: true,
  preflightValidatorAvailable: true,
  packetStatus: 'STRUCTURALLY_VALID_BUT_NOT_AUTHORIZED',
  readyToCompile: false,
  readyForTraining: false,
  realCustomerEvidenceAvailable: false,
  realCustomerReadinessPassed: false,
  externalApiDefault: false,
  oracleLabelAuthority: 'deterministic_origin_oracle',
  requiredInputs: [
    'customer evidence authorization',
    'customer site evidence manifest',
    'customer hard cases',
    'redaction status',
    'SHA-256 provenance',
    'review approval',
  ],
  originOutputs: [
    'customer-owned hard-case holdout',
    'verified labels',
    'policy evaluation report',
    'included/excluded evidence review log',
    'evidence bundle manifest',
    'claim-boundary report',
  ],
  blockedByDefault: [
    'real customer readiness',
    'training without explicit authorization',
    'external API use',
    'unapproved evidence',
    'pending-redaction evidence',
    'missing-provenance evidence',
  ],
  evidenceLayers: [
    { layer: 'Synthetic demo hard cases', claim: 'mechanics only' },
    { layer: 'Generated counterfactual robustness', claim: 'curriculum evidence only' },
    { layer: 'Authorized local fixture', claim: 'gate mechanics only' },
    { layer: 'Real approved design-partner evidence', claim: 'only after approval and eval gates pass' },
  ],
  allowedClaim:
    'Origin has a fail-closed evidence contract and a blank packet ready for a real design partner to submit approved evidence.',
  blockedClaim: 'Real customer readiness.',
  claimBoundary:
    'The intake package freezes the evidence contract. It does not imply real customer data exists, does not unlock training, and does not certify a robot.',
} as const
