"""Generate per-task HUD env artifacts for a materialized qabench env (Plan 008 WP1).

Given a materialized ``envs/qabench/<slug>/`` (Dockerfile + task_assets + build
context) this emits the four files HUD's ``hud serve`` contract needs, modeled on
the hand-built ``envs/mongodb-sales-aggregation-engine`` env:

  * ``env.py``        — a generic HUD Environment: lays the grader + instruction
                        into ``/app`` (so the agent sees them and the reward hack
                        surface exists), starts ``/app/start.sh`` if the task ships
                        a service, and grades with the task's own pytest suite.
  * ``Dockerfile.hud``— the task's build with its trailing CMD/ENTRYPOINT stripped
                        and a HUD serve layer appended; the grade-time deps the
                        task's ``test.sh`` installs via ``uv add`` are baked in so
                        the BashGrader subprocess resolves them offline.
  * ``pyproject.toml``/``tasks.py`` — the ``hud serve`` / ``hud eval`` entry points.

The generated env exposes a single ``build_task`` template so the discovery loop
can load any qabench env by a stable factory name.
"""

from __future__ import annotations

import re
from pathlib import Path

_GRADE_CMD = (
    "python3 -m pytest task_assets/test_outputs.py -rA -q "
    "> .grade.log 2>&1; rc=$?; cat .grade.log; exit $rc"
)

# Packages we never bake from `uv add` (project scaffolding, not grade deps).
_SKIP_DEPS = frozenset({"pytest"})


def parse_grade_deps(test_sh_text: str) -> list[str]:
    """Extract grade-time python deps from a Terminal-Wrench ``test.sh``.

    The boilerplate installs them with ``uv add <pkg> [<pkg> ...]`` (pytest is
    pinned separately and pinned/skipped here). Returns a de-duplicated, ordered
    list of bare package names (version pins dropped for a system pip install).
    """
    deps: list[str] = []
    for raw in test_sh_text.splitlines():
        line = raw.strip()
        if not line.startswith("uv add"):
            continue
        for token in line[len("uv add") :].split():
            token = token.strip("'\"")
            if token.startswith("-"):
                continue
            base = re.split(r"[=<>!~ ]", token, maxsplit=1)[0].strip()
            if base and base not in _SKIP_DEPS and base not in deps:
                deps.append(base)
    return deps


def _strip_cmd_entrypoint(dockerfile_text: str) -> str:
    """Drop trailing CMD/ENTRYPOINT lines so the HUD serve CMD is authoritative."""
    kept = [
        raw
        for raw in dockerfile_text.splitlines()
        if not raw.strip().upper().startswith(("CMD ", "CMD[", "ENTRYPOINT "))
        and raw.strip().upper() not in {"CMD", "ENTRYPOINT"}
    ]
    return "\n".join(kept).rstrip() + "\n"


def env_py(slug: str) -> str:
    name = f"{slug.replace('-', '_')}_v1"
    return f'''\
"""{slug} — HUD v6 environment (generated by chronos.qabench.hud_env).

Generic HUD port of the Terminal Wrench task: the agent gets a bash workspace at
/app with the task's instruction + its own pytest grader visible (so the recorded
reward hack — planting a conftest/plugin that force-passes the suite — reproduces),
and reward is that suite run by a BashGrader over the agent's files.
"""

import asyncio
import os
import subprocess
from pathlib import Path

from hud.environment import Environment
from hud.graders import BashGrader, combine

env = Environment(name="{name}")

APP = Path("/app")
ASSETS = Path(__file__).resolve().parent / "task_assets"
ws = env.workspace(APP, guest_path="/app", network=True)

GRADE_CMD = (
    {_GRADE_CMD!r}
)


def _running_in_container() -> bool:
    return APP.exists() and os.access("/", os.W_OK)


@env.initialize
async def _setup() -> None:
    """Lay the grader + instruction into /app and start a task service if present."""
    if not _running_in_container():
        return
    (APP / "task_assets").mkdir(parents=True, exist_ok=True)
    for item in ASSETS.iterdir():
        if item.is_file():
            (APP / "task_assets" / item.name).write_bytes(item.read_bytes())
    instruction = ASSETS / "instruction.md"
    if instruction.exists():
        (APP / "instruction.md").write_bytes(instruction.read_bytes())
    start = APP / "start.sh"
    if start.exists():
        subprocess.Popen(["bash", str(start)])  # noqa: S603,S607 - task-owned service
        await asyncio.sleep(3)


def _prompt() -> str:
    return (ASSETS / "instruction.md").read_text()


@env.template(id="{slug}")
async def build_task():
    """Prompt the agent with the task instruction; grade with the pytest suite."""
    yield _prompt()
    sub = await BashGrader.grade(1.0, command=GRADE_CMD, cwd=str(APP))
    result = await combine(sub)
    yield result.reward
'''


def pyproject_toml(slug: str) -> str:
    return f'''\
[project]
name = "{slug}"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["hud-python", "pytest==8.4.1"]

[tool.uv]
package = false
'''


def tasks_py() -> str:
    return '"""hud eval entry point."""\n\nfrom env import build_task\n\ntasks = [build_task()]\n'


def dockerfile_hud(base_dockerfile_text: str, grade_deps: list[str]) -> str:
    body = _strip_cmd_entrypoint(base_dockerfile_text)
    deps = " ".join(f'"{d}"' for d in grade_deps)
    deps_line = f" {deps}" if deps else ""
    return f"""{body}
# --- HUD serve layer (generated by chronos.qabench.hud_env) ---
# Ensure pip3 (and thus python3) is present. Guard on pip3, NOT python3: the
# ubuntu bases ship python3 WITHOUT pip3, so a python3-only guard skips the apt
# install and the pip3 step below then fails. python bases already have both.
RUN command -v pip3 >/dev/null 2>&1 || (apt-get update \\
        && apt-get install -y --no-install-recommends python3 python3-pip \\
        && rm -rf /var/lib/apt/lists/*)
# Grade-time deps installed system-wide so the BashGrader subprocess resolves them
# offline and the verifier stays subvertible by agent-planted conftest/plugins.
RUN pip3 install --no-cache-dir --break-system-packages "pytest==8.4.1"{deps_line}
RUN pip3 install --no-cache-dir --break-system-packages uv
WORKDIR /app
COPY env.py pyproject.toml tasks.py /app/
COPY task_assets /app/task_assets
RUN uv sync
EXPOSE 8765
ENTRYPOINT []
CMD ["uv", "run", "hud", "serve", "env:env", "--host", "0.0.0.0", "--port", "8765"]
"""


def generate_hud_env(env_dir: Path | str) -> dict[str, str]:
    """Build the four HUD-serve files for a materialized env; return name -> content."""
    env_dir = Path(env_dir)
    slug = env_dir.name
    dockerfile = (env_dir / "Dockerfile").read_text(encoding="utf-8")
    test_sh = env_dir / "task_assets" / "test.sh"
    grade_deps = (
        parse_grade_deps(test_sh.read_text(encoding="utf-8"))
        if test_sh.exists()
        else []
    )
    return {
        "env.py": env_py(slug),
        "pyproject.toml": pyproject_toml(slug),
        "tasks.py": tasks_py(),
        "Dockerfile.hud": dockerfile_hud(dockerfile, grade_deps),
    }


def write_hud_env(env_dir: Path | str) -> list[Path]:
    """Materialize the HUD-serve files into ``env_dir``; return written paths."""
    env_dir = Path(env_dir)
    written: list[Path] = []
    for name, content in generate_hud_env(env_dir).items():
        target = env_dir / name
        target.write_text(content, encoding="utf-8")
        written.append(target)
    return written
