"""Modal ForkPoint capture + sterile restore for the qabench Δ run (Plan 008, 008-owned).

Reuses Plan 002's proven Modal primitives — ``modal.Image.from_dockerfile`` (builds a
HUD image in Modal with no registry push), ``Sandbox.create`` + ``snapshot_filesystem``
(capture), ``Image.from_id`` (restore) — against a materialized qabench env, WITHOUT
the mongodb-specific quiesce (mongod fsync) or ``/data/db`` state roots. It produces the
ForkPoint dict ``branch_runs`` forks from (piece 1), and restores a branch's snapshot to
run the 008 sterile ``clean_verify`` referee in an offline sandbox (piece 2).

The Modal calls are real spend + require MODAL credentials; the dict/tar helpers are pure
and unit-tested. ``ModalCleanVerifyRunner`` satisfies the ``seams.CleanVerifyRunner``
protocol, so it drops into the scorer exactly like the local docker runner.
"""

from __future__ import annotations

import base64
import hashlib
import io
import json
import tarfile
from pathlib import Path
from typing import Any

_APP_NAME = "chronos-qabench"
_RESTORE_TRUSTED_ROOT = "/opt/clean_verify"


def _exec(
    sandbox: Any, command: str, *, timeout: int = 300, check: bool = True
) -> tuple[int, str]:
    proc = sandbox.exec("bash", "-lc", command, workdir="/app", timeout=timeout)
    proc.wait()
    output = proc.stdout.read() + proc.stderr.read()
    if check and proc.returncode != 0:
        raise RuntimeError(
            f"sandbox command failed rc={proc.returncode}: {output[-1000:]}"
        )
    return proc.returncode, output


def _hud_image(env_dir: Path) -> Any:
    import modal

    return modal.Image.from_dockerfile(
        str(env_dir / "Dockerfile.hud"), context_dir=str(env_dir)
    )


def qabench_task_profile(
    env_module_path: str, *, factory: str = "build_task"
) -> dict[str, Any]:
    """The ``hud_task_profile`` a qabench ForkPoint carries for Plan 003 ``branch_runs``.

    Every qabench env is generated by ``hud_env.py`` with one fixed serve/grade contract
    — ``env:env`` entrypoint, ``build_task`` factory, ``_prompt`` prompt, ``/app`` workdir,
    the task's own pytest grader, and the sterile ``clean_verify`` pre-grader — so the
    capture records it inline and the ForkPoint is self-describing (``branch_runs`` loads
    the task entirely from this profile, no out-of-band env contract).
    """
    return {
        "env_module_path": env_module_path,
        "task_factory": factory,
        "prompt_factory": "_prompt",
        "runtime_workdir": "/app",
        "instruction_path": "/app/task_assets/instruction.md",
        "trusted_entrypoint_ref": "env:env",
        "pre_grader_command_argv": [
            "python",
            "-m",
            "pytest",
            "-p",
            "no:cacheprovider",
            "--confcutdir",
            "task_assets",
            "-q",
            "task_assets",
        ],
        "grader_command_argv": [
            "python3",
            "-m",
            "pytest",
            "task_assets/test_outputs.py",
            "-rA",
            "-q",
        ],
    }


def forkpoint_dict(
    env_dir: Path | str, snapshot_id: str, *, state_roots: tuple[str, ...]
) -> dict[str, Any]:
    """Build the ForkPoint record ``branch_runs`` consumes (pure; testable)."""
    env_dir = Path(env_dir)
    slug = env_dir.name
    payload = {
        "schema_version": 1,
        "snapshot_id": snapshot_id,
        "snapshot_mode": "filesystem",
        "snapshot_restore_ref": f"modal-image://{snapshot_id}",
        "snapshot_retention": "modal-default-ttl",
        "task_id": slug,
        "environment_version": f"{slug.replace('-', '_')}_v1",
        "task_state_roots": list(state_roots),
        "hud_task_profile": qabench_task_profile(f"envs/qabench/{slug}/env.py"),
        "network_policy": "block_network=True",
        "fork_reason": "qabench-fresh-task-boundary",
        "trace_kind": "fresh-task-state",
    }
    payload["fork_point_id"] = (
        "fp-"
        + hashlib.sha256(json.dumps(payload, sort_keys=True).encode()).hexdigest()[:24]
    )
    return payload


def capture_forkpoint(
    env_dir: Path | str,
    *,
    state_roots: tuple[str, ...] = ("/app",),
    app_name: str = _APP_NAME,
    cpu: float = 1.0,
    memory: int = 2048,
) -> dict[str, Any]:
    """Build the env's HUD image in Modal, snapshot it, and return the ForkPoint dict."""
    import modal

    env_dir = Path(env_dir)
    app = modal.App.lookup(app_name, create_if_missing=True)
    sandbox = modal.Sandbox.create(
        "sleep",
        "infinity",
        image=_hud_image(env_dir),
        app=app,
        block_network=True,
        secrets=[],
        cpu=cpu,
        memory=memory,
        timeout=900,
        workdir="/app",
        tags={
            "chronos_plan": "008",
            "purpose": "qabench_forkpoint_capture",
            "task": env_dir.name,
        },
    )
    try:
        _exec(sandbox, "sync")  # quiesce the filesystem before the snapshot
        snapshot = sandbox.snapshot_filesystem()
    finally:
        sandbox.terminate()
    return forkpoint_dict(env_dir, snapshot.object_id, state_roots=state_roots)


def trusted_assets_tar_b64(env_dir: Path | str) -> str:
    """gzip+base64 the trusted referee bundle (task_assets/ + clean_verify.sh)."""
    env_dir = Path(env_dir)
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz") as tar:
        tar.add(env_dir / "task_assets", arcname="task_assets")
        tar.add(env_dir / "clean_verify.sh", arcname="clean_verify.sh")
    return base64.b64encode(buf.getvalue()).decode()


def _snapshot_id_of(workspace_ref: str) -> str:
    return workspace_ref.rsplit("//", 1)[-1] if "//" in workspace_ref else workspace_ref


class ModalCleanVerifyRunner:
    """Restore a branch's Modal snapshot and run the sterile clean_verify referee.

    Satisfies ``seams.CleanVerifyRunner`` (``run(workspace_ref) -> bool``);
    ``workspace_ref`` is a branch's ``snapshot_restore_ref`` (``modal-image://im-…``).
    The trusted grader + entrypoint are injected fresh from the 008 env (NOT taken from
    the agent's snapshot), and the sandbox is offline (``block_network=True``).
    """

    def __init__(self, env_dir: Path | str, *, app_name: str = _APP_NAME) -> None:
        self.env_dir = Path(env_dir)
        self.app_name = app_name

    def run(self, workspace_ref: str) -> bool:
        import modal

        snapshot_id = _snapshot_id_of(workspace_ref)
        app = modal.App.lookup(self.app_name, create_if_missing=True)
        sandbox = modal.Sandbox.create(
            "sleep",
            "infinity",
            image=modal.Image.from_id(snapshot_id),
            app=app,
            block_network=True,
            secrets=[],
            cpu=1.0,
            memory=2048,
            timeout=600,
            workdir="/app",
            tags={"chronos_plan": "008", "purpose": "qabench_clean_verify"},
        )
        try:
            tar_b64 = trusted_assets_tar_b64(self.env_dir)
            _exec(
                sandbox,
                f"mkdir -p {_RESTORE_TRUSTED_ROOT} && "
                f"printf %s {tar_b64} | base64 -d | tar -xzf - -C {_RESTORE_TRUSTED_ROOT}",
            )
            rc, _ = _exec(
                sandbox,
                f"CLEAN_VERIFY_TESTS={_RESTORE_TRUSTED_ROOT}/task_assets "
                f"bash {_RESTORE_TRUSTED_ROOT}/clean_verify.sh",
                check=False,
            )
        finally:
            sandbox.terminate()
        return rc == 0
