// Types for the FactoryDad-1 web bundle (src/factorydad/data.json), generated by
// factorydad1/export_web.py. The dashboard only renders this — it computes nothing.

export type Terminal = 'finish' | 'escalate' | 'refuse'
export type Difficulty = 'core' | 'hard'

export interface Cell {
  x: number
  y: number
}

export interface DroidIntent {
  skill: string
  object: string
  goal: string
}

export interface MvtecScan {
  object_category: string
  scan_status: 'normal' | 'anomaly' | 'uncertain'
  anomaly_type: string
  severity: 'none' | 'low' | 'medium' | 'high' | 'critical'
}

export interface Workspace {
  grid: { width: number; height: number }
  start: Cell
  item: Cell
  drop: Cell
  hazards: Cell[]
  human_only: Cell[]
  obstacles: Cell[]
  battery: number
  max_steps: number
}

export interface Case {
  case_id: string
  title: string
  factory_story: string
  droid_intent: DroidIntent
  mvtec_scan: MvtecScan
  workspace: Workspace
  scan_required: boolean
  urgency_note: string | null
  allowed_actions: string[]
  difficulty: Difficulty
  oracle_terminal: Terminal
  oracle_rationale: string
  preferred_actions: string[]
  failure_tags: string[]
}

export interface Metrics {
  n: number
  success_rate: number
  false_accept_rate: number
  false_reject_rate: number
  missed_scan_rate: number
  invalid_json_rate: number
  reward_mean: number
}

export interface SubsetMetrics {
  n: number
  metrics: Metrics
  rsl_tier: string
}

export interface PerCase {
  case_id: string
  oracle_terminal: Terminal
  model_terminal: Terminal | null
  reward: number
  failure_tags: string[]
}

export interface FailureRow {
  case_id: string
  prompt_summary: string
  model_actions: string[]
  oracle_terminal: Terminal
  model_terminal: Terminal | null
  reward: number
  failure_tags: string[]
  correction: string
  preferred_actions: string[]
  rejected_actions: string[]
  rsl_impact: string
  training_use: string
}

// A requested model we cannot run here yet (no API access). Shown honestly as
// pending — NO fabricated numbers, no projected tier — just what it needs to run.
export interface PendingModel {
  id: string
  label: string
  needs: string
}

export interface Scorecard {
  benchmark: string
  benchmark_version: string
  model: string
  is_reference: boolean
  /** 'measured' = a real oracle-scored run is on disk. Absent on the reference. */
  evidence?: 'measured' | 'projected'
  /** ISO date the run was produced (shown as "last tested"). */
  evaluated_date?: string
  task_count: number
  terminal_counts: Record<Terminal, number>
  metrics: Metrics
  rsl_tier: string
  rsl_label: string
  rsl_note: string
  breakdown: {
    by_difficulty: Record<Difficulty, SubsetMetrics | null>
    by_terminal: Record<Terminal, SubsetMetrics | null>
  }
  per_case: PerCase[]
  failure_rows: FailureRow[]
}

export interface Bundle {
  benchmark: string
  version: string
  tiers: Record<string, string>
  terminal_counts: Record<Terminal, number>
  difficulty_counts: Record<Difficulty, number>
  cases: Case[]
  reference: Scorecard
  scorecards: Record<string, Scorecard>
  pending_models: PendingModel[]
  hud_runs: { agent: string; job_url: string; success_rate: number; rsl_tier: string }[]
  harness_runs: {
    agent: string
    task_count: number
    success_rate: number
    false_accept_rate: number
    rsl_tier: string
  }[]
  failure_examples: FailureRow[]
  dataset_boundary: { droid: string; mvtec: string; note: string }
  disclaimer: string
}
